node {
   def commit_id
   //We have two options, 1: to SCM from Pipeline Script from SCM, 2: Use our own declartive Github repo
   stage('checkout'){
      git branch: 'master',
          url: 'https://github.com/yanivomc/docker-cicd.git'
   }
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("michabi/jenkins-lab:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 michabi/jenkins-lab:latest
      docker kill docker_test
      '''
     }
}

