node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('DockerBuild') {
       dir("advance/multistage_build/"){
       sh "ls"
       sh "docker build --target builder -t yroh1/jenkins-lab:multi_stage_builder -f Dockerfile-pipelines ."
       }
     }
   stage('Linting') {
       dir("advance/multistage_build/"){
       sh "ls"
       sh "docker build --target linting -t yroh1/jenkins-lab:multi_stage_test -f Dockerfile-pipelines ."
       }
    }
   stage('push') {
      dir("advance/multistage_build/"){
      sh "docker login -u yroh1 -p passwordfr12" 
      sh "docker build -t yroh1/jenkins-lab:multi_stage_test -f Dockerfile-pipelines . --network=multistage_build_nexus"
      sh "docker push yroh1/jenkins-lab:multi_stage_test"
      }
   }

}
   
   




