version: '3.1'
services:
    jenkins:
        build: ./jenkins/master
        image: jenkins-jb/master:3.0
        container_name: jenkins-master
        ports:
            - '8080:8080'
            - '50000:50000'
        environment:
            - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
        networks: 
            - jb
        volumes:
            - ./jenkins/master/casc.yaml:/var/jenkins_home/casc.yaml
    jenkins-slave:
        build: ./jenkins/slave
        image: jenkins-jb/slave:1.0
        # Removed container name to support scale out option 
        #container_name: jenkins-slave 
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - jb
        depends_on:
            - jenkins

networks: 
  jb: