node {
  def commit_id
   stage('Checkout') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('docker MultiStage build/push') {
     dir("advance/workshop/talkshow") {
      def flask_image = docker.build("michabi/jenkins-lab:${commit_id}", "--build-args USERNAME=${env.BUILD_USER_ID}, '.'")
      docker.withRegistry('https://index.docker.io/v1/', 'docker_hub') {
        flask_image.push()
      }
     }
   }
   stage('docker run') {
     flask_image.run()
   }
}